name: menu_recommendation_app
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=3.1.3 <4.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_barcode_scanner: ^2.0.0
  flutter_launcher_icons: ^0.13.1
  flutter_profile_picture: ^2.0.0
  flutter_svg: ^2.0.7
  get: 4.6.6
  get_storage: ^2.1.1
  http: ^1.1.0
  image_picker: ^1.0.4
  intl: ^0.18.1
  qr_flutter: ^4.1.0
  string_extensions: ^0.6.12
  transitioned_indexed_stack: ^1.0.2
  url_launcher: ^6.1.14

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/app_icon.png"

flutter:
  assets:
    - assets/icons/
    - assets/models/
  uses-material-design: true
